""""""""""""""""""""
" Configuration
""""""""""""""""""""

syntax on " Syntax highlighting
colorscheme dracula
set background=dark

"filetype plugin indent on
set wrap " Wrap lines
set ttyfast
set mouse= " Allow clicking with the mouse
set laststatus=2
set number " Show line numbers
set relativenumber
set incsearch
set hlsearch
set hidden " Don't force save on buffer switch
set tabstop=2 " Show existing tab with 2 spaces width
set expandtab " On pressing tab, insert 2 spaces

set foldmethod=indent " Fold all code based on indent
set foldenable " Fold all files automatically on open
set foldnestmax=5 " Nest a maximum of 5 times
set shiftwidth=2 " Fold starting from 2 spaces

""""""""""""""""""""
" Plugins
""""""""""""""""""""

" For now we use vim-plug (https://github.com/junegunn/vim-plug)
call plug#begin('~/.vim/my_plugins')
" Ripgrep integration
Plug 'jremmen/vim-ripgrep'
" Dracula theme
Plug 'dracula/vim', { 'as': 'dracula' }

" fzf - Find files easily
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

" Install CtrlP
Plug 'ctrlpvim/ctrlp.vim'

" Install Nerdtree
Plug 'preservim/nerdtree'

" Fancy status lines
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

""""""""""""""""""""
" Keymaps
""""""""""""""""""""

" Leader aliases for buffer navigation
let mapleader = " "

" Open Nerdtree
map <Leader>t :NERDTreeToggle<CR>

" Map fzf to Leader-f
:nnoremap <Leader>f :GitFiles<CR>

" List buffers
nmap <Leader>l :ls <cr>

" Save with Leader s
:nnoremap <Leader>s :w<CR>
:nnoremap <Leader>S :wq<CR>
:nnoremap <Leader>q :q<CR>

" Switch Buffer
nmap <Leader>1 :1b<cr>
nmap <Leader>2 :2b<cr>
nmap <Leader>3 :3b<cr>
nmap <Leader>4 :4b<cr>
nmap <Leader>5 :5b<cr>
nmap <Leader>6 :6b<cr>
nmap <Leader>7 :7b<cr>
nmap <Leader>8 :8b<cr>
nmap <Leader>9 :9b<cr>

" Close buffer
:nnoremap <Leader>c :bd<CR>

" Cycle through buffers
:nnoremap <Leader><Leader> :bnext<CR>:redraw<CR>:ls<CR>

:nnoremap <Leader><Tab> :bnext<CR>:redraw<CR>:ls<CR>

:nnoremap <Leader><S-Tab> :bprevious<CR>:redraw<CR>:ls<CR>

" Map Rg for easy access
:nnoremap <C-S-f> :Rg 

"""""""""""""""""""""
