dynamic_title: true
font: 
  normal:
    family: Calling Code
  bold:
    family: Calling Code
  italic:
    family: Calling Code
  bold_italic:
    family: Calling Code
  size: 20.0
key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
