dynamic_title: true
font:
  normal:
    family: CodeNewRoman Nerd Font Mono
  bold:
    family: CodeNewRoman Nerd Font Mono
  italic:
    family: CodeNewRoman Nerd Font Mono
  bold_italic:
    family: CodeNewRoman Nerd Font Mono
  size: 20.0
hints:
  enabled:
    - hyperlinks: true
      regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      mouse:
        enabled: true
        mods: None
      command: open
key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left, mods: Alt, chars: "\x1BB" }
  - { key: Equals, mods: Command|Shift, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: N,  mods: Command, action: SpawnNewInstance }
