dynamic_title: true
font: 
  normal:
    family: FiraCode Nerd Font Mono
  bold:
    family: FiraCode Nerd Font Mono
  italic:
    family: FiraCode Nerd Font Mono
  bold_italic:
    family: FiraCode Nerd Font Mono
  size: 20.0
key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left,  mods: Alt, chars: "\x1BB" }
