[window]
dynamic_title = true

[font]
size = 20.0

[font.bold]
family = "CodeNewRoman Nerd Font Mono"

[font.bold_italic]
family = "CodeNewRoman Nerd Font Mono"

[font.italic]
family = "CodeNewRoman Nerd Font Mono"

[font.normal]
family = "CodeNewRoman Nerd Font Mono"

[[hints.enabled]]
command = "open"
hyperlinks = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"
