dynamic_title: true
font:
  normal:
    family: CodeNewRoman Nerd Font Mono
  bold:
    family: CodeNewRoman Nerd Font Mono
  italic:
    family: CodeNewRoman Nerd Font Mono
  bold_italic:
    family: CodeNewRoman Nerd Font Mono
  size: 20.0
key_bindings:
  - { key: Right, mods: Alt, chars: "\x1BF" }
  - { key: Left, mods: Alt, chars: "\x1BB" }
  - { key: Equals, mods: Command|Shift, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
hints:
  enabled:
    - hyperlinks: true
      regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
              [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      mouse:
        enabled: true
        mods: None
      command: open
# Copied from:
# https://github.com/alacritty/alacritty-theme/blob/master/themes/rose-pine-moon.yaml
colors:
  primary:
    background: "0x232100"
    foreground: "0xe0def4"
  cursor:
    text: "0xe0def4"
    cursor: "0x56526e"
  vi_mode_cursor:
    text: "0xe0def4"
    cursor: "0x56526e"
  line_indicator:
    foreground: None
    background: None
  selection:
    text: "0xe0def4"
    background: "0x44415a"
  normal:
    black: "0x393552"
    red: "0xeb6f92"
    green: "0x3e8fb0"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xea9a97"
    white: "0xe0def4"
  bright:
    black: "0x6e6a86"
    red: "0xeb6f92"
    green: "0x3e8fb0"
    yellow: "0xf6c177"
    blue: "0x9ccfd8"
    magenta: "0xc4a7e7"
    cyan: "0xea9a97"
    white: "0xe0def4"
  hints:
    start:
      foreground: "#908caa"
      background: "#2a273f"
    end:
      foreground: "#6e6a86"
      background: "#2a273f"
