""""""""""""""""""""
" Configuration
""""""""""""""""""""

" Overall look of the editor
syntax on " Syntax highlighting
set background=dark
set termguicolors
set nowrap " Wrap lines
set ttyfast
set mouse= " Allow clicking with the mouse
set laststatus=2
set number " Show line numbers
set relativenumber " Set line numbers to relative.
set incsearch
set hlsearch
set hidden " Don't force save on buffer switch
set tabstop=2 " Show existing tab with 2 spaces width
set expandtab " On pressing tab, insert 2 spaces
set nohlsearch " When done searching, don't keep things highlighted.
set scrolloff=8 " Start scrolling 8 lines from the top/bottom, instead of the very bottom.
set cmdheight=2 " Two lines for command output.
set signcolumn=yes " Show a column at before line numbers, for git and LSP messages and stuff.

" Folding
set foldmethod=indent " Fold all code based on indent
set foldenable " Fold all files automatically on open
set foldnestmax=5 " Nest a maximum of 5 times
set shiftwidth=2 " Fold starting from 2 spaces

" Saving and Undo
set noswapfile " Don't create the crap .swp files.

""""""""""""""""""""
" Keymaps
""""""""""""""""""""

" Leader aliases for buffer navigation
let mapleader = " "

" List buffers
nmap <Leader>l :ls <cr>

" Save with Leader s
:nnoremap <Leader>s :w<CR>
:nnoremap <Leader>S :wq<CR>
:nnoremap <Leader>q :q<CR>

" Switch Buffer
nmap <Leader>1 :1b<cr>
nmap <Leader>2 :2b<cr>
nmap <Leader>3 :3b<cr>
nmap <Leader>4 :4b<cr>
nmap <Leader>5 :5b<cr>
nmap <Leader>6 :6b<cr>
nmap <Leader>7 :7b<cr>
nmap <Leader>8 :8b<cr>
nmap <Leader>9 :9b<cr>

" Close buffer
:nnoremap <Leader>c :bd<CR>

" Cycle through buffers
:nnoremap <Leader><Leader> :bnext<CR>:redraw<CR>:ls<CR>

:nnoremap <Leader><Tab> :bnext<CR>:redraw<CR>:ls<CR>

:nnoremap <Leader><S-Tab> :bprevious<CR>:redraw<CR>:ls<CR>

" Map Rg for easy access
:nnoremap <C-S-f> :Rg 

