# Set locale correctly
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# Plugins
#source ~/completions.zsh
source ~/dotfiles/aliases/header.sh

if [[ -f "~/dotfiles/configs/hidden/zshrc.*" ]]; then
  source ~/dotfiles/configs/hidden/zshrc.*
fi

# fzf config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS='--height 20% --layout=reverse --border'


# Powerlevel10k customization
#typeset -g POWERLEVEL9K_VCS_HIDE_TAGS=true

## Persistent history
HISTSIZE=15000              #How many lines of history to keep in memory
HISTFILE=~/.zsh_history     #Where to save history to disk
SAVEHIST=15000              #Number of history entries to save to disk
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    sharehistory      #Share history across terminals
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

# Path updates
PATH="$PATH:/usr/local/bin"
PATH="$PATH:~/bin"

## Node Version Manager
#export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
#alias load_nvm="[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" # This loads nvm"

# Editor config
EDITOR=nvim

# Git Manager Stuff
alias gog='cd $(gtm find)'
alias ggo='cd $(gtm find)'
alias gop="gtm find "

bindkey -e
bindkey "^[a" beginning-of-line
bindkey "^[e" end-of-line
bindkey "[b" backward-word
bindkey "[f" forward-word
bindkey "^[[3~" delete-char

export COURSIER_CREDENTIALS="$HOME/.config/coursier/credentials.properties"

# Go setup
export GOPATH=$HOME/go
arch=$( uname -m )
if [[ "${arch}" == "arm64" ]]; then
  brew_prefix="/opt/homebrew/opt"
else
  brew_prefix="/opt/brew/opt"
fi
export GOROOT="${brew_prefix}/golang/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Starship prompt
# https://starship.rs/presets/
eval "$(starship init zsh)"
